spring:
  application:
    name: service-b
server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://eureka-registry:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      leaf: true

logging:
  level:
    io.ztbeike.ffr4ms: debug