FROM openjdk:11-jre

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

ADD ./target/zuul-gateway-1.0-SNAPSHOT.jar /app/
CMD ["java", "-Xmx200m", "-jar", "/app/zuul-gateway-1.0-SNAPSHOT.jar", "--spring.profiles.active=b"]

EXPOSE 8050