spring:
  application:
    name: zuul-gateway-b
  cache:
    ehcache:
      config: classpath:ehcache.xml
  cloud:
    loadbalancer:
      retry:
        enabled: true
server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://eureka-registry:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      gateway: service-b

zuul:
  RibbonRoutingFilter:
    route:
      disable: true
  routes:
    zuul:
      path: /frecovery/**
      service-id: zuul-gateway

    basic:
      path: /serviceB/**
      service-id: service-b
      strip-prefix: false
  sensitive-headers:

ribbon:
  ConnectionTimeout: 10000
  ReadTimeout: 600000

logging:
  level:
    io.ztbeike.ffr4ms: debug
