apiVersion: v1
kind: Service
metadata:
  name: eureka-registry
spec:
  type: NodePort
  selector:
    app: eureka-registry
  ports:
  - port: 8030
    targetPort: 8030
    nodePort: 30803
    protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
  - port: 8060
    targetPort: 8060
---

apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
  - port: 8070
    targetPort: 8070
---

apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway-a
spec:
  type: NodePort
  selector:
    app: zuul-gateway-a
  ports:
  - port: 8040
    targetPort: 8040
    nodePort: 30804
    protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway-b
spec:
  selector:
    app: zuul-gateway-b
  ports:
  - port: 8050
    targetPort: 8050
    protocol: TCP