spring:
  application:
    name: zuul-gateway-a
  cache:
    ehcache:
      config: classpath:ehcache.xml
  cloud:
    loadbalancer:
      retry:
        enabled: true
server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  RibbonRoutingFilter:
    route:
      disable: true
  routes:
    zuul:
      path: /zuulApi/**
      service-id: zuul-gateway

    basic:
      path: /serviceA/**
      service-id: service-a
      strip-prefix: false
  sensitive-headers:

ribbon:
  ConnectionTimeout: 10000
  ReadTimeout: 600000

info:
  getway: service-a
  port: ${server.port}